@startuml
skinparam Linetype ortho
entity "entity1" as e1{
    *e1_id : number <<generated>>
    --
    *name : text
    description : text
}

entity "entity2" as e2{
    *e2_id : number <<generated>>
    --
    *e1_id : number <<FK>>
}

' e1||..|{e2
e1"1"--"*"e2
@enduml